### ISSUE TITLE
experimental tray icon not working

### ISSUE THREAD

**Issue by willwhitney** [yakyak/yakyak#116]
The icon specified at https://github.com/yakyak/yakyak/blob/master/src/main.coffee#L115 isn't present, so the tray icon doesn't reflect the read state. I just put this into my copy of the app using these (pulled from Hangouts and cleaned up a bit):

icon_read@2x
![icon_read@2x.png](https://cloud.githubusercontent.com/assets/597829/12495524/2f2e010a-c05e-11e5-888d-7a4e2d5698f7.png)
icon_unread@2x
![icon_unread@2x.png](https://cloud.githubusercontent.com/assets/597829/12495525/2f2e9fac-c05e-11e5-86a5-832691fde515.png)

Using the @1x.png / @2x.png naming scheme lets Electron pick the right one automatically.

Also, I noticed that the tray image update code at https://github.com/yakyak/yakyak/blob/master/src/main.coffee#L274 isn't present in the release version of the app. Maybe the .coffee didn't get compiled?

P.S. this app is a tremendous improvement over the Google clients for Hangouts. I seriously appreciate the effort, and I expect I'll make some PRs as I continue to use it!

**Comment by davibe** [comment]
You are correct. Infanct the released version has that code commented. I just forgot to push it. The original author of the patch did send me the icons later so i will put this back on. Also, your icons seem better than the ones i have because they are back and white. Just a bit blurry. Will try them thank you.

I am looking forward to some PRs don't be shy!

**Comment by davibe** [comment]
https://github.com/yakyak/yakyak/commit/479b2334c787e02f9a82b365f60cff7d60adb805

**Comment by davibe** [comment]
this should work in the upcoming 1.1.3
