### ISSUE TITLE
Windows - when minimized to taskbar and clicking pinned icon the app doesn't open from taskbar.

### ISSUE THREAD

**Issue by MostHated** [yakyak/yakyak#1162]
Hey there, 
    I really like the app, but there is a bit of an issue. When I minimize/close the window to the taskbar and I go to click on my icon that is pinned the taskbar app stays closed. I have to go to the running task icon in the corner and open it from there. It feels like clicking on the pinned icon should open it up?

Thanks,
-MH

**Comment by averissimo** [comment]
I don't have windows installed.

I'd challenge you to try and fix that and then submit a pull request.

That can probably be solved at `src/ui/views/trayicon.coffee`

**Comment by MostHated** [comment]
If I find myself with some extra time to look it over to see if it might be something I can figure out, I surely will, but I am not familiar with Coffee, Electron, or any of the listed technologies involved with the application, unfortunately. I just use Google Hangouts a lot.

**Comment by chomper700** [comment]
Because of the way the Windows "Pin to Taskbar" functionality works, a more straightforward way to describe this issue would be "if you launch yakyak.exe while it is already running _but it is minimized to the tray icon (notification area)_, it doesn't display the active instance, but it should".

If I had to **_guess_** how to fix this, it would involve editing the following section of `src/main.coffee`.

```
# If someone tries to run a second instance, we should focus our window.
app.on 'second-instance', (event, commandLine, workingDirectory) ->
    if mainWindow
        mainWindow.restore() if mainWindow.isMinimized()
        mainWindow.focus()
```

I don't know this programming language and am just piecing together logic from other areas, so consider this pseudocode, but there would be need to be some sort of addition, possibly simply just `mainWindow.show()`, or possibly something more like `if mainWindow && !mainWindow.isVisible() then mainWindow.show()`.

If I understood how to build electron apps, I'd figure it out for myself, but it's all a little overwhelming for me.

**Comment by chomper700** [comment]
Just to clarify: this is the issue you're describing. (Right?) Starting from a state in which YakYak is running, but has been "closed to tray".

![image](https://user-images.githubusercontent.com/30938242/84823597-9d095a80-afec-11ea-8c03-211cd43b6bf7.png)

(If so, my above understanding is correct. Clicking the left one causes Windows to launch a new instances of yakyak.exe, which ultimately does nothing, while clicking the right one directly triggers `mainWindow.show()` within YakYak itself, which works.)

**Comment by MostHated** [comment]
Yes, you were 100% correct in your explination. 

Using Discord as an example. You have the window opened, you click X to close it and it remains running in the notification area. Opening it again from a shortcut, start menu, pinned icon, etc, detects that there is already an instance of the process running and simply shows the existing process window instead of launching a new process.

**Comment by MostHated** [comment]
Bumping, due to the fact that this still occurs.

**Comment by MostHated** [comment]
Closing this, because I started using something else anyways.

**Comment by averissimo** [comment]
@chomp7001 that was exactly the solution, next time create a pull request :-)

Even if you're not familiar with the language a pull request will create a discussion on what can be improved on the implementation.

**Comment by averissimo** [comment]
To build yakyak you only need to have nodejs installed, download the code and run `npm install` and then `npm start` to start the application with the local code
