### ISSUE TITLE
Google Voice SMS Messages do not send - Text is Grey

### ISSUE THREAD

**Issue by TeddJohnson** [yakyak/yakyak#1169]
Creating a new ticket for issue #822 

I had made a comment there but the issue remained "closed", so I'm filing a new one.

"I get this issue all the time. I'm on 1.5.4

This happens on SMS for Google Voice, both 1-on-1 and Group Texts.

The weird part is that the messages still show up when I go to Gmail and look at hangouts directly, but the recipient never receives the message that is gray on Yak-yak"

**Comment by StevensNJD4** [comment]
To add, it seems to happen after the initial outgoing text on program start.

**Comment by averissimo** [comment]
None of the developers ever used google voice sms.

If someone wants to volunteer their time to try and fix this we would welcome any pull request.

**Comment by aseering** [comment]
I'm hitting this issue as well, except with Google Fi rather than Google Voice.  (I think their implementations are pretty similar under the hood?)

I've checked out and built the yakyak code.  It seems like this is probably something at the network protocol layer; does anyone have any pointers to where the relevant code lives in the yakyak codebase, or anything that would be worth trying?

**Comment by pokropski** [comment]
I have also been having this problem. Would really appreciate a fix. Can help with texting or whatnot.

**Comment by dmbream** [comment]
+1. 

On multiple occasions, I’ve responded to an SMS thread via the app on a Mac. It appears in grey. I’ll sometimes see the message in the thread on my phone in Hangouts for iOS afterward, but then the recipient will tell me they never received the message. It’s problematic, as some messages appear to go through, while others don’t. Doesn’t exactly inspire confidence in Yak Yak. Any help would be appreciated. 

Thanks in advance.
