### ISSUE TITLE
v1.5.9 can't connect

### ISSUE THREAD

**Issue by JasonMiesionczek** [yakyak/yakyak#1202]
Just updated to 1.5.9 on my mac and it can't connect.

**Comment by averissimo** [comment]
Was it a network problem? I see no problems in Linux environment.

**Comment by sowenjub** [comment]
Same here, I reinstalled 1.5.8.

**Comment by averissimo** [comment]
I can't replicate this, could you guys start Yakyak from the command line and then screenshot it?

Example.

![image](https://user-images.githubusercontent.com/211358/86653625-9e271980-bfe5-11ea-9626-37343570620c.png)

**Comment by averissimo** [comment]
@sowenjub did an older version connect while a more recent one couldn't?

That is strange as there should be no differences in how the recent versions of yakyak connect _(v1.5.7 / v1.5.8 / v1.5.9 / v1.5.10-beta-rolling)_

The differences between all those versions are on the UI and not on the backend.

**Comment by sowenjub** [comment]
I reinstalled 1.5.9 by downloading it here since I couldn't find a way to trigger the "update" notification from within the app and it works.
I guess it's the update process that messed things up somehow.

Just to clarify what I did:
- was using 1.5.8 (not downloaded from Github, it was an update of an older version since I installed it on this MB in 2019)
- got the inside notification "a new version is available, please update to 1.5.9" (or something like that :p), clicked on it and it stopped working at this point, even after quitting the app and restarting it
- downloaded 1.5.8 from Github and replaced the app (dropped in /Application) and it worked again
- downloaded 1.5.9 from Github and replaced the app (dropped in /Application) and it kept working (quit and restarted, no connection issue)
