### ISSUE TITLE
Images Missing in Chats

### ISSUE THREAD

**Issue by smartinec** [yakyak/yakyak#1380]
MacOS Big Sur 11.6
YakYak v1.5.11.5

Images are no longer showing in the chat window. I can't see sent or received images. I checked hangouts.google.com and it's working fine. See below:
![2021-11-17_17-13-18](https://user-images.githubusercontent.com/1090227/142291492-ef7533c6-5492-487e-8c09-06f3de1f5b61.png)

**Comment by jakeface1** [comment]
I have the same issue on my M1 Mac Mini. Images wont send or load.

**Comment by claviger** [comment]
It's not just a MacOS issue. On Windows 11, the same thing happened starting 5-6 days ago; images are missing from received messages, and sending images doesn't work (the "uploading image" spinner just spins forever.)

**Comment by HomerSp** [comment]
Sorry for the super late reply, I've been busy and haven't had any time to look at this issue. I've updated the beta to hopefully fix this issue, so please test it and let me know if it works - thanks!

**Comment by smartinec** [comment]
MacOS Big Sur 11.6.1
YakYak v1.5.12-beta

Still not working for me. Now the URL shows, but the image doesn't. Also, the scrollbar colors are off in dark mode.

![image](https://user-images.githubusercontent.com/1090227/146554028-cd83a920-b765-4e70-9e60-67c7d4e41ae1.png)

**Comment by HomerSp** [comment]
Hmm, I added some code to make it show the url if it's unable to preload the thumbnail, which seems like what's happening here. Are you able to open the link by clicking on it? I unfortunately can't reproduce it, but my guess would be that it's, for some reason, failing to authenticate (you have to be logged in to open attachments). I have no idea why this is happening though, because all of the required authentication cookies and such should be set.
Does this happen for all images?

**Comment by smartinec** [comment]
I am able to view the image in my browser by clicking on the link. Yes, it happens for all images.

I turned on the inspector and it's getting a 302 response for all images that redirects to ServiceLogin. After that it attempts a ServiceLogin request that succeeds. That returns a response like this:

```
continue=https://lh3.google.com/hangouts/AMSf6AEvoadONg0MsQ50eZhEmfEY2xwDTp5joDdcYY6IMz333fX_I9HS2BY%3Dw2160-h2880&hl=en
```

But, the "continue" URL is never attempted in the network window.

**Comment by HomerSp** [comment]
Very weird, it isn't supposed to redirect you to a ServiceLogin page - it only does that if you're not logged in. The ServiceLogin page is html, asking you to sign in, so that explains why it isn't continuing.
I've added some more test code to the latest beta, but I don't think that's going to work since it's redirecting you to the ServiceLogin page.
Did you try signing out and signing back in through yakyak? The cookies may be messed up thinking you aren't logged in. Though if it works normally otherwise, I'm not sure.

**Comment by smartinec** [comment]
Logging out and back in fixed the image issue in both current release and beta. Sorry I didn't try that sooner. Google recently forced 2FA, so maybe it's related to that.

**Comment by smartinec** [comment]
I should also note that image clicks (to open in browser) don't work in released version, but are working in beta version.

**Comment by HomerSp** [comment]
Thanks for confirming - I'm glad it's fixed now!
