### ISSUE TITLE
Notification for "NEW Contact" is missing

### ISSUE THREAD

**Issue by sw360cab** [yakyak/yakyak#15]
the client does not catch any notification regarding a contact not in the list.
It's needed to add the contact from "Hangout" and after typing message it is involved in YakYak

**Comment by algesten** [comment]
can you perhaps give us a step by step instruction of how to reproduce this?

**Comment by sw360cab** [comment]
Yes.

- A new contact tries to write me on Hangouts
- Hangouts (Google) propose the option to Add/Block the contact, which may have already written me
- Yakyak is unaware of that until I add the contact on Hangout

**Comment by xori** [comment]
I'm going to bet this won't be fixed until someone does some investigation for the `reply_to_invite` event in https://github.com/algesten/hangupsjs

Until then the quick fix I used was to customize my invite settings so that anyone can contact me without an invitation. Until I get heaps of spam, it works for now. You could also just enable that to start a conversation with a new person, then turn it off again.

**Comment by algesten** [comment]
right. i guess i must have the invite-settings so anyone can contact, because when i was looking at this, i never ever got the `reply_to_invite` or `invitation_watermark`.

if anyone want to try figure it out, i pushed some code in master that `console.log` the events if they happen.
