### ISSUE TITLE
1.2.1 Issues

### ISSUE THREAD

**Issue by x-tk** [yakyak/yakyak#185]
Few bugs it seems:

1 - not all the names resolve (some conversations show email addresses)
2 - pictures are not being displayed
3 - do not see settings to enable dark mode, new version reverted back to light mode

**Comment by Durpn** [comment]
On windows 7 x64, opening yakyak causes a window-opening loop with all blank windows. This continues forever and does not resolve itself.

**Comment by deantoader** [comment]
I'm getting an infinite Electron window loop on OSX 10.11.5 upon opening the app.

**Comment by psouza4** [comment]
Infinite loop here too -- only happened when I deleted the local data/cache.  Happens when run with non-elevated and elevated contexts.  Does not happen if I restore my local data/cache for the application (I deleted it because I'm missing thumbnails for users and thought it'd help).

**Comment by davibe** [comment]
I am uploading 1.2.2 which should fix the infinite windows in start (thx @fbaew). I am on a slow connection so be patient.

Dark mode was removed. We have a pending pull request for a better version of it in #160 
I wanted to wait for it to be ready but then i decided to do a new release because of #159 which should be fixed

I marked 1.2.1 as a pre-release so others will not update. Thank you for reporting and please open separate issues.
