### ISSUE TITLE
Enter key does not send when emojis are open

### ISSUE THREAD

**Issue by drzero42** [yakyak/yakyak#198]
Release: 1.2.3
OS: OSX 10.11.5

When typing out a message, it can normally be sent, by pressing enter. When I open the emojis subwindow, enter now produces newlines, instead of sending the message. I have to close the emojis subwindow, by pressing the emoji-button again, and click in the message-field before enter will send the message, instead of making a newline.

**Comment by davibe** [comment]
if you enter twice it is sent then, right ?

**Comment by drzero42** [comment]
You are absolutely correct, it does send when pressing it twice.

**Comment by davibe** [comment]
ty

**Comment by ctcpip** [comment]
Just want to add that this only happens when pressing enter immediately following an emoji character.  If you type any character, including a space, then press enter, it sends the message.  The emoji subwindow always stays open though, which should not stay open after a message is sent.  It should automatically close.

OS/Desktop: Linux / LXDE
