### ISSUE TITLE
Missing Timestamp on current message

### ISSUE THREAD

**Issue by sw360cab** [yakyak/yakyak#22]
When I am in a chat, the messages received does not display a timestamp

**Comment by davidbanham** [comment]
This is by design. Each "conversation" gets a timestamp rather than each individual message.

![screen shot 2015-06-27 at 5 44 22 pm](https://cloud.githubusercontent.com/assets/631832/8391044/45619b5c-1cf4-11e5-99d5-6d4e85f4d01e.png)

What's your use case for individual message timestamps? Tell us a little more about the issue you're having and we'll figure out a way to solve it.

**Comment by algesten** [comment]
two thoughts. the grouping has some time setting of how much time passes before we consider it a new group. don't know if that could use some tweaking?

we could perhaps make each comment div have a title attribute with the timestamp which means you'd see it on hover. dunno if that would be irritating or not.

**Comment by sw360cab** [comment]
@davidbanham  That's not how "Hangouts" works...Each portion of message gets how long time passed from the time message was sent. Then we can discuss upon "1min ago", respect @ hh:mm. 
Skype does the same, Whatsapp too, and any chat client should report this (but that's IMHO)

In any case this is not to be intended as an issue but as an enhancement. So repo's admins may "label" this as enhancement.

**Comment by algesten** [comment]
apple's message app does it this way. less clutter.

**Comment by averrin** [comment]
Imho, its important information, but it may be hidden until message will be hovered.
