### ISSUE TITLE
Reflow text for narrower windows

### ISSUE THREAD

**Issue by wigster** [yakyak/yakyak#229]
Currently (Yakyak 1.3.0, Windows 10), when the window is made narrower than ~1000 pixels the right edge of the conversation pane disappears. 

Would it be possible to squeeze the empty space between the right and left chat bubbles instead of scrolling it off? Or is that what Google sends from its servers and cannot be altered?

**Comment by davibe** [comment]
can you provide screenshots ?

**Comment by wigster** [comment]
[https://1drv.ms/i/s!Aq44GeJ_w3olht1TuGlJ-US3Z0X3Ew](Try this.)

**Comment by wigster** [comment]
[Try this.](https://1drv.ms/i/s!Aq44GeJ_w3olht1TuGlJ-US3Z0X3Ew)

This is the full window, when I shrink it horizontally.

**Comment by davibe** [comment]
oh my. That should not happen. It does not happen on other platforms

**Comment by wigster** [comment]
In case it has some sort of impact, I am running on a 4k screen with 150% DPI scaling.

**Comment by ZackBoe** [comment]
I'm also seeing this, but only occasionally, on Debian 8.

I've run into a couple somewhat related issues as well with the otherwise wonderful new design:
- Absurdly long group names (dont ask) should be truncated somehow
- Conversation list now shows less on screen, doesn't fully hide text when shrunk to its minimum

Lemme know if you want me to open separate issues for either of these.

All three issues are present here:
![0e1c1fc3](https://cloud.githubusercontent.com/assets/904055/16162456/a1fb7818-34a1-11e6-97ba-ebc84f8547bf.png)
For comparison:
![c6bdabf1](https://cloud.githubusercontent.com/assets/904055/16162474/b938aa00-34a1-11e6-9c45-43a08efacffa.png)

**Comment by davibe** [comment]
for the moment you don't need to open separate issues. I just want to raise attention of @arnriu. Mabe he has some ideas.

**Comment by arnriu** [comment]
@davibe Yes sir, I have ;p

**Comment by davibe** [comment]
Why would those 2 lines fuck up things?

**Comment by arnriu** [comment]
Those 2 lines tells that the view has been updated and, among other things (DOM manipulation, models update, ...), redraw the whole applayout. It's very heavy, and we do not need to do that on resize nor move.
Well, one can say, we do not need to do that, but what's the big deal? We call this often. When we change current conversations, add new one, etc... Even on app start. And it never hang the whole application.

As I said, those operation are very heavy. When we update the viewstate on conversation change, it's called once. It's ok, we cand do heavy stuff once in a while without overloading main processor. But when we resize or move, this is how often it's called (I just replaced these 2 lines with console log). Sometimes twice a millisecond !

![resize](https://cloud.githubusercontent.com/assets/9418756/16172064/ffe79a04-357f-11e6-8faf-6f8e7c119927.png)

**Comment by davibe** [comment]
redrawing is not as heavy as you think. We have a virtualdom in place and we only redraw things that changed. I suspect there is some kind of loop (resize caused by handling resize) or race condition (redrawing while redrawing). Maybe it's an electron bug on windows.

I suspect at some point it could be useful to redraw while resizing.
A better solution would be to throttle the resize handling using http://underscorejs.org/#throttle.
This way we don't loose the redraw functionality and at the same time we don't do it too often.

**Comment by arnriu** [comment]
Yeah, I know, its not THAT heavy, I was just making a point :) . But its not free either, and doing it every millisecond is way too much for the system.
And I still don't see a use case where resize / move should redraw. We store new window size in local storage for further use, and that's it. We could (should?) throttle or debounce it anyway.
