### ISSUE TITLE
Feature Request: Actionable MacOS Notifications

### ISSUE THREAD

**Issue by naher94** [yakyak/yakyak#324]
It would be great it there was a way to reply and cancel and click on the notification and jumps to that conversation #

**Comment by davibe** [comment]
does node-notifier allows us (the lib we're using) to do that ?

**Comment by averissimo** [comment]
it does, although it depends on the underlying operating system's notification method

if someone wants to pick this up the library is node-notifier as @davibe said, and the code is in `src/ui/views/notifications.coffee`

**Comment by austin-guevara** [comment]
Big want! If this is implemented, there should be 3 possible interactions to a notification:

**Primary:** Reply (opens reply window, doesn't require switching to app)
**Secondary:** Ignore (closes notification)
**Clicking on the notification, not the button:** activates the window, opens that conversation.

**Comment by brankoenero** [comment]
Hey there!
I'm seeing that this issue is not closed. 
I'll try to implement it. I doesn't seams difficult at all.
I didn't touch this technology but seams really similar to other multi-platforms frameworks.
Theres someone that can help me for installation. I cloned the project and I did "npm install", but shows a lot of error messages.

> npm WARN prefer global marked@0.3.6 should be installed with -g

> bufferutil@1.1.0 install /Users/brankofuenzalidalorca/Development/repos/yakyak/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:
In file included from ../../nan/nan.h:82:
../../nan/nan_new.h:34:56: warning: 'ToInt32' is deprecated [-Wdeprecated-declarations]
To<v8::Int32>(v8::Handle<v8::Integer> i)   { return i->ToInt32(); }
                                                       ^
/Users/brankofuenzalidalorca/.node-gyp/6.9.5/include/node/v8.h:8202:21: note: 'ToInt32' has been explicitly marked
      deprecated here
Local<Int32> Value::ToInt32() const {
                    ^
In file included from ../src/bufferutil.cc:16:
In file included from ../../nan/nan.h:82:
../../nan/nan_new.h:39:56: warning: 'ToUint32' is deprecated [-Wdeprecated-declarations]
To<v8::Uint32>(v8::Handle<v8::Integer> i)  { return i->ToUint32(); }
                                                       ^
/Users/brankofuenzalidalorca/.node-gyp/6.9.5/include/node/v8.h:8196:22: note: 'ToUint32' has been explicitly marked
      deprecated here
Local<Uint32> Value::ToUint32() const {
                     ^
In file included from ../src/bufferutil.cc:16:
In file included from ../../nan/nan.h:82:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:49:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                            ^
/Users/brankofuenzalidalorca/.node-gyp/6.9.5/include/node/v8.h:4007:56: note: 'New' has been explicitly marked deprecated
      here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                       ^
In file included from ../src/bufferutil.cc:16:
In file included from ../../nan/nan.h:82:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:166:30: warning: 'Compile' is deprecated [-Wdeprecated-declarations]
  return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &src);
                             ^
... and more...
> 

Thanks.

**Comment by averissimo** [comment]
there are some modules that do not compile and give warnings during `npm install`

bufferutil is one of them and utf-8-validate is another

it is expected, as long as it is a warning in the end:

![image](https://cloud.githubusercontent.com/assets/211358/25657774/d1d76cc2-2fff-11e7-8fcf-7a1433918903.png)
