### ISSUE TITLE
Dock conversations like old hangouts UI used to do before they ruined it

### ISSUE THREAD

**Issue by fancellu** [yakyak/yakyak#370]
This is an enhancement.

i.e. https://productforums.google.com/forum/#!topic/hangouts/MGMWc2gZ6pw

Currently yakyak act v much like the new hangouts, which doesn't have the old docking conversations.

**Comment by davibe** [comment]
i don't like "docking"

**Comment by stacia** [comment]
I think you're going to be getting a lot of "refugees" from the previous Hangouts version in chrome. Even if you don't like the feature, it's something a lot of people liked about the old Hangouts plugin and most likely will be requesting here unless Google somehow rolls back the changes.

**Comment by MarkTiedemann** [comment]
Can confirm. The removal of docking is actually the reason why I tried YakYak in the first place. Would love to see it added.

**Comment by MarkusMcNugen** [comment]
Same here, would love to see it added if possible. Google really screwed up with that and has made my life a living hell in our call center... where we use Hangouts as our primary chat client. Really interrupts the flow of work when you have to switch to a different window just to reply to a message really quick.

**Comment by atomicthumbs** [comment]
this would be pretty great. as is, being able to run the old hangouts extension is the only reason I still have Chrome installed - and I seem to be having issues with that.

**Comment by fancellu** [comment]
How to get old hangouts back, with docking

https://www.reddit.com/r/google/comments/51umbr/hangouts_extension_finally_updated/d7fb2gd

**Comment by MarkusMcNugen** [comment]
Thanks fancellu for that find. That helped a lot actually. I probably should have thought about developer mode... I'd still like to see it added to YakYak, or a quick reply notification if using Windows 10, but it's your application so do as you please! lol. Thanks again!

**Comment by victorstuber** [comment]
@fancellu OMG thank you so much for this

**Comment by nsudds** [comment]
I found Yakyak for this exact reason too --- because of the latest update to Google Hangouts.   I want to be able to have conversations popped out not in a single conversation window for sure and docking can be a benefit but it's great when it's optional too so it better suits everyone.   I'll be watching how this app develops for sure.  

Thanks to @fancellu for the way to get the old hangouts back, that's awesome -- until they fully remove it or listen to users to improve the new version.

**Comment by mliq** [comment]
@MarkusMcNugen - workflow with YakYak is actually much faster than docking, because you can't use the keyboard with docking. Chatting requires the keyboard, and having to switch from the keyboard to the mouse twice (if you want to hide the window afterwards) each time you interact with chat is a significant waste of time and movement. 

Try this workflow: 
* Switch to YakYak and back to what you were doing: <kbd>Alt</kbd>+<kbd>Tab</kbd> on Windows, <kbd>Cmd</kbd>+<kbd>Tab</kbd> on Mac.
* Navigate quickly between conversations: <kbd>Alt</kbd>+<kbd>1-9</kbd> on Windows, <kbd>Cmd</kbd>+<kbd>1-9</kbd> on Mac.
* Cycle next/previous conversation with <kbd>Ctrl</kbd>+<kbd>j/k</kbd> on Windows, <kbd>Ctrl</kbd>+<kbd>Tab</kbd> on Mac.
* Also you may cycle with <kbd>Cmd</kbd>+<kbd>Up/Down Arrow</kbd> on Mac, not sure about Windows on that one.

**Comment by atomicthumbs** [comment]
I would prefer to be able to look at two conversations at once.

**Comment by mliq** [comment]
@atomicthumbs I see, that makes sense. My sense is that implementing hangouts-style docking would be a large undertaking, however it might be possible to allow multiple yakyak windows or pop-out conversations to a separate window with less work? What do you think @davibe?

**Comment by fancellu** [comment]
@mliq When we say we want hangouts style tabbing, that's what we want. Please don't tell us that we shouldn't want it. If you don't like it, fine, no one is forcing it on you. Hangouts refugees LOVE the tabbing.

**Comment by mliq** [comment]
@fancellu I'm sorry, I really didn't mean to imply that you are wrong for wanting that. I was specifically responding to @MarkusMcNugen need for workflow speed and trying to be helpful by offering suggestions for how one could achieve that with YakYak as it currently is. 

I am also trying to determine a way for building towards the functionality that you all desire, with the consideration that @davibe is one of the 2 main authors and does not like docking.

**Comment by atomicthumbs** [comment]
The thing I specifically like about the docking is the fact that I can have one or two conversations, shrunk to a few pixels high, hovering just above my taskbar, and when I mouseover them they expand a bit to show the title. I can click on them to activate them, and if I receive a message, they pop up like the mouseover and turn green, showing me who sent me a message. It allows me to keep a conversation going as I research things (as one example), without having to switch back and forth between windows and conversations.

**Comment by mliq** [comment]
https://github.com/old-hangouts/old-hangouts-chrome-extension

**Comment by fancellu** [comment]
@mliq Now is broken, by Google doing something evil. More evil.

https://github.com/old-hangouts/old-hangouts-chrome-extension/issues/2
