### ISSUE TITLE
Missing dock icon (Mac OS)

### ISSUE THREAD

**Issue by pablocruz23** [yakyak/yakyak#436]
I was playing around with YakYak and chose to remove it as a dock icon (not really sure what that would do). The result is, it no longer appears in my dock. But it also means the only way I can return to YakYak is by launching the application again from my Applications folder. And now none of the YakYak menus appear when the application is running, so I don't have access to the View menu to get the dock icon back.

I tried deleting the application and re-installing it, but the problem remains. Any way I can get the dock icon back?

**Comment by averissimo** [comment]
I think the option in Mac is called "Hide Dock icon" in the View menu.

Have you tried using the menu button to open the menus? (sorry if it sounds like a dumb question)

![image](https://cloud.githubusercontent.com/assets/211358/20141296/95c311de-a687-11e6-8632-29676c4c67f6.png)

If you have tried this, my only suggestion this far is to open inspector by pressing `Command+Alt+I` and then write in the console tab: `window.localStorage.hidedockicon`

if it is "true", then write in console the command below and restart YakYak:

`window.localStorage.hidedockicon = "false"`

ps. Not a Mac user so my help in this issue is limited

**Comment by averissimo** [comment]
@pablocruz23 if you really want it back you can delete the YakYak user directory under:

it should be called `yakyak`

![image](https://cloud.githubusercontent.com/assets/211358/20141865/37426b52-a68a-11e6-9d11-12701364987f.png)

**Comment by pablocruz23** [comment]
Actually, I found the answer.

I couldn't go through the View menu, because when you choose to remove the dock icon, for some crazy reason you don't get any of the YakYak menus. That is, when you have YakYak in the foreground, the top menus are from whatever application you were on previously.

However, in the top bar, there's an icon for YakYak which allows you to add the dock icon again. So I'm all set.

Thanks!

**Comment by averissimo** [comment]
@pablocruz23 You're welcome :) can you close this issue then?
