### ISSUE TITLE
Not orienting photos properly

### ISSUE THREAD

**Issue by sbjustin** [yakyak/yakyak#45]
When displaying a photo uploaded by another person in the conversation the photo is not oriented based on the EXIF data.  Photo appears oriented correctly via google chat web interface though.

**Comment by algesten** [comment]
Something like this would probably help https://github.com/GritDesign/node-jpegorientation and I suspect the fastest rotation UI wise would be to just use CSS rotate transforms (not actually rotate the data).

**Comment by davibe** [comment]
@algesten can you please shoot and send me one portrait and one landscape picture ? Please pick some nice subject :D

**Comment by algesten** [comment]
![img_0376](https://cloud.githubusercontent.com/assets/227204/9705145/d664fa56-54ba-11e5-9301-4d36a803d338.jpg)
![img_0377](https://cloud.githubusercontent.com/assets/227204/9705146/d9e67984-54ba-11e5-8719-bfc1fbd56db6.jpg)

**Comment by davibe** [comment]
are you kidding me, i wanted you to send them to me on Yakyak :package: 
I am sorry for the elephant, it looks angry.

**Comment by algesten** [comment]
oh

**Comment by davibe** [comment]
i received 2 pictures from @algesten and they were ok. I guess a lot depends on how the photos are saved (i.e. which camera app is used) because some devices may save rotated data, other may usa exif data. So far i was not able to reproduce. 

@sbjustin can you please add me on hangout and send me 2 pics so i can reproduce this ? This is me https://plus.google.com/u/0/+DavideBertola
ty
