### ISSUE TITLE
Videos shared from other people in chat are still image only

### ISSUE THREAD

**Issue by danmandle** [yakyak/yakyak#535]
A friend shared an uploaded video with me. In YakYak it previews a still image with a play button. Upon clicking the image, it opens the still image with the superimposed play button in a browser. When clicking the same thing in Hangouts, it opens, then redirects the link to the actual video.

**Comment by davibe** [comment]
which version are you using ? how did the guy send the video ? can someone send a video to me the same way so i can reproduce the issue ? :D

**Comment by averissimo** [comment]
@davibe videos can be sent via the android app and I think via the webinterface by choosing a video _(I believe I did the latter one once, but not 100% sure)_

I'll send you a video in a short while

**Comment by davibe** [comment]
i found where the actual video url is. The problem is that this url requires the user to be logged. 

When using google services on the main browser one cam be logged with many accounts at once. When navigating to different google services the urls have an index to know which account you're using. For example `gmail.com/u/0/...` and `gmail.com/u/1/...`. The ids are actually indexes and depend on the order of logins you performed in your browser

Yakyak only logs-in as one single user. The video url we receive may not match the url of the logged user in the main browser. Sicne we open the urls in the main browser it may or may not work.

I think it works only if you are logged one single user and it's the same you use in yakyak.

One solution (painful) could be to open contents directly in yakyak. I have tried creating a new window (`window.open`) but the new windows does not share the same session/cookie as the main one.

Hmm..

**Comment by davibe** [comment]
The video url we get from google requires authentication but it redirects to an un-aunthenticated one. We could modify hangupsjs to add a method to perform the first authenticated http request for us and retrieve the final url it redirects to. Then the final url could be open in the external browser.

I had a look at hangupsjs apparently this needs to be implemented in the `ChatReq` and exposed at `Client` level

Here is an example. Yakyak receives this
- https://plus.google.com/u/3/photos/albums/pgf13jocroaeltkdarjm1co380vcbfli8?pid=6374318644773096706&oid=105346544122646337367

which redirects to this
- https://r6---sn-hpa7zn7y.googlevideo.com/videoplayback?id=1e7397d2a6f34ccb&itag=22&source=picasa&begin=0&requiressl=yes&mm=30&mn=sn-hpa7zn7y&ms=nxu&mv=m&nh=IgpwcjAxLm1pbDAyKgw3Mi4xNC4yMTEuNjg&pl=21&sc=yes&mime=video/mp4&lmt=1484136737888760&mt=1484146143&ip=2.230.111.239&ipbits=8&expire=1484175055&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,nh,pl,sc,mime,lmt&signature=701A059490D3FF042DB5DAD9A73A16F01DBF0D45.51E7CDA55C39EA1A44B3EFF9A413D3EBE88CD78C&key=ck2

**Comment by davibe** [comment]
I managed to workaround this on the client (renderer) side but i still think it the url-resolving logic should be implemented in hangupsjs at some point.
