### ISSUE TITLE
can't logout

### ISSUE THREAD

**Issue by uman242** [yakyak/yakyak#560]
After clicking "logout" Yakyak doesn't logout nor close. Can't send messages though. 
But after "quit" next launch is logged in.
yakyak-1.4.2-win32-x64, win7 x64

**Comment by davibe** [comment]
will test, thank you

**Comment by LuizJa** [comment]
Same here with versión 1.4.2, can't log out either.

**Comment by averissimo** [comment]
what happens when you loggout?

for me the window is closed and a login window appears. If I quit and open yakyak again the same login window appears.

![outs9zhs6fyq1](https://cloud.githubusercontent.com/assets/211358/23963022/db09027a-09a7-11e7-9c95-b950a9235730.gif)

@LuizJa @uman242 can you open Yakyak via the command line and screenshot it after logout

Something like this:

![image](https://cloud.githubusercontent.com/assets/211358/23963117/3203745c-09a8-11e7-875f-1a80fef77fc2.png)

**Comment by LuizJa** [comment]
![2017-03-16_15h29_38](https://cloud.githubusercontent.com/assets/629237/24021667/3f31d288-0a5f-11e7-9c21-47e421ae6d10.gif)
This is what happen, i don't know if this helps you.

**Comment by uman242** [comment]
it looks like this, after logout I get "WARN no SAPISID cookie"
![screenshot - 2017-03-17 08_05_41](https://cloud.githubusercontent.com/assets/22954424/24032526/c5b69242-0ae8-11e7-87df-4c8b5b71b369.png)

**Comment by averissimo** [comment]
@LuizJa the idea was to launch from command line and to look at the messages as @uman242 shows.

@uman242 only those, no exception being thrown? :\

are you guys using a normal gmail.com account?

**Comment by uman242** [comment]
yes, only this. What do you mean normal? I think it's normal. I can do the same at home, if there's something more, I will put it here.

**Comment by LuizJa** [comment]
Maybe is because is windows doesn't do it the same way but it shows nothing as you can see in the gif above.
The account is a GSuite account with 2 step verification.
