### ISSUE TITLE
Ubuntu 16.10 Tray Icon Issues - Square with X & Unread Message Behavior

### ISSUE THREAD

**Issue by TimmyzBeach** [yakyak/yakyak#575]
When switching between conversations, the tray icon flashes to a black box with a red "X" in it, and then back to the normal grey icon. 

Additionally, the tray icon only illuminates to the green (you have an unread message) color _after_ selecting that unread conversation, which of course in a couple of seconds returns to the normal grey icon after the application determines that the message has now been read.

Ubuntu 16.10 x64
Kernel 4.9.0-040900
YakYak v1.4.2 (latest)

**Comment by averissimo** [comment]
I confirm this. It is an electron issue where changing the trayicon image (even to the same) will have a transitional stage where the black box with the red 'X' appears.

I believe I minimized the number of times this happens in the #567 pull request (by only changing the icon if the state changes)

Things to test before submitting to electron/electron:

- [x] Using a `native image` instead of a path (in case the blank box is shown while image is being created)
- [ ] Calling tray from the main process instead of the renderer

**Comment by averissimo** [comment]
Created issue in electron/electron https://github.com/electron/electron/issues/8582
