### ISSUE TITLE
YakYak fails to connect if the user hasn't had at least 1 conversation prior to usage

### ISSUE THREAD

**Issue by SapphireTactician** [yakyak/yakyak#640]
Shout out to @kirill133 for isolating this one! See title, YakYak gets stuck at "Connecting..." if the user hasn't had at least 1 conversation in Hangouts prior to using YakYak.

**Comment by roncemer** [comment]
I'm having the same problem.  Just installed the newest version two days ago, and it looked as if it was going to work.  Now it just hangs at "Connecting" with the three animated dots below it.

Come on, folks.  Can't we get a WORKING Hangouts client for Linux?  You know, something reliable, because I need this for my work.

**Comment by averissimo** [comment]
@roncemer the solution so far is to add a new conversation using the web interface
