### ISSUE TITLE
Create transparent interface (messenger-like)

### ISSUE THREAD

**Issue by kirkerafael** [yakyak/yakyak#676]
Hangouts allow for transparent user interface, when contacts are just avatar circles and conversation disappears when not focused. It is nice, minimalist look.

Would it be possible to have something similar with yakyak?

**Comment by averissimo** [comment]
Can you post a screenshot?

**Comment by kirkerafael** [comment]
Sure so: http://imgur.com/a/D9YTa

**Comment by averissimo** [comment]
I see now.

Yakyak has a design choice of keeping a single window instead of docking as old hangouts interface and seems like the new one is also doing (to some degree)

there has been some conversation on this issue: (about docking) #370

And improvements on UI are being discussed here: #605 

To create a transparent interface (as an option or default) we would need someone that is passionate about this and wishes to contribute!

The framework that we use for the interface allows for borderless windows and some really neat stuff so I don't think there is a technical constraint... we just need the manpower :)
