### ISSUE TITLE
Can we please have auto correct in this app?

### ISSUE THREAD

**Issue by tonypg1** [yakyak/yakyak#754]
So far this is the best google hangout app I have used. And it's free! If you could add the auto correct function in it that would be perfect! 

Thanks.

**Comment by PMiner** [comment]
Electron is based on chromium, and chromium has some auto-correct pre-installed, so maybe that could be enabled?

**Comment by averissimo** [comment]
**Duplicate issue of #61**

@PiFi Sorry for the late answer to this issue. The problem here is this feature requires independent compilation on Windows, Mac and Linux (with windows being the big problem, see screenshot below)

I'm keeping this issue close, as there is already an open issue #61 (quite old)

![image](https://user-images.githubusercontent.com/211358/34911155-d3ac1220-f8bb-11e7-8452-165d8560826a.png)
