### ISSUE TITLE
New messages not appearing when using Hangouts on iOS

### ISSUE THREAD

**Issue by LucasVanDongen** [yakyak/yakyak#824]
I have an iPhone SE still on the latest version of iOS 10 with the official Google Hangouts client. If I don't use that client I get all new messages in YakYak. However if I use it and / or get notifications on my iOS client the messages won't appear in YakYak. I am not sure what triggers it but it seems like if a push notification is sent to my device YakYak doesn't get it.

**Comment by bilgekaan** [comment]
same with Iphone 5s

**Comment by averissimo** [comment]
- Do those conversation have history turned off?
- Do they still appear in gmail's web interface?
- If you quit YakYak and start it again do they suddenly appear?

This is strange as YakYak asks the hangouts server for the last messages and listens for new ones.

**Comment by LucasVanDongen** [comment]
1) not sure. But they appear everywhere I log in so I guess they're not private
2) yes
3) I think they did


It's like they're immediately flagged as read

**Comment by averissimo** [comment]
Oh, **it is different if the problem is not that messages are missing, but they are marked as read.**

If you read messages elsewhere then they will be marked as read in YakYak. In YakYak we do not actually monitor the unread status in the application, we just check with the server.

Even the bubble is only removed because we send to the hangouts server that the user has read all messages up until the current time and get an update on the read status from the server.

If they are actual missing *(not being shown at all even when opening the conversation, then that should be a problem)*

I don't have an iphone so I cannot actually check on this.

**Comment by brendandebeasi** [comment]
This is certainly still an issue. It occurs when YakYak is running on my mac.
