### ISSUE TITLE
Notifications not appearing on Mac

### ISSUE THREAD

**Issue by wallwhit** [yakyak/yakyak#865]
I'm new to YakYak since finding that High Sierra does not support Hangsouts / Google Talk in Messages. YakYak is a good substitute. Thanks!

On one of my Macs, the OS notifications do not appear. The app's dock badge shows properly, and if I enable YakYak's custom sound, I hear it, but there's no OS banner or alert. 

On my other Mac, running the same version of macOS (10.13.2) and the same version of YakYak (1.5.0), the notifications work fine.

Here's my configuration of View >> Pop-up Notification:

<img width="349" alt="screen shot 2018-01-26 at 13 09 27" src="https://user-images.githubusercontent.com/35851871/35460891-606ed2a0-029a-11e8-921c-707178ddb16b.png">

Any idea how to fix that?

Thanks

**Comment by averissimo** [comment]
Our pre-releases are being updated as new code is merged. This means that v1.5.0 might not be the same on both systems.

Can you try to donwload v1.5.0 again and test it?

If it happens then open the console (Ctrl + Alt + i) and check the if the console tab has any errors *(or exceptions).*

**Comment by averissimo** [comment]
Also check if the global mac options on notifications have yakyak disabled by some reason.

We do not have a custom notification system, but use Mac's notification system.

**Comment by averissimo** [comment]
If you want to go all the way, when opening the console write the following code in the console tab:

´´´
notifier = require('node-notifier');
notifier.notify('bla bla bla, this should appear in notifications');
´´´

**Comment by wallwhit** [comment]
Sorry for my delay. Downloading v1.5.0 today and using it fixed it. Thanks!

**Comment by jscribbles** [comment]
I'm having this same issue with High Sierra 10.13.5 on the latest release for Mac YakYak 1.5.1.

YakYak doesn't show up in the Notification settings to turn on or off. To be fair, I'm having the same issue with some other Third Party apps, but covering my bases and posting here in case it is an issue on this end. Thanks!

**Comment by jscribbles** [comment]
Going to reply to myself here. After figuring out what was going on with other apps, I believe the problem has nothing to do with YakYak. And in fact is not a problem at all. It's just a slightly strange native behavior from macOS.

Essentially, for a third party app to appear in your System Preferences > Notifications menu, the app has to first attempted to send a notification. I haven't received any messages over Google Hangouts (and thus in YakYak) since installing, and therefore that hasn't triggered macOS to place it in the Notifications menu yet.

Sorry for the false alarm!
