### ISSUE TITLE
3rd party authentication prompt not shown

### ISSUE THREAD

**Issue by rcosma-gd** [yakyak/yakyak#91]
Hi - I use a hosted account, which means that after entering the user@domain on first use window I get a simple login pop-up that goes to the company server and then the OAUTH creds are forwarded to Google. In general all apps work, but Yakyak doesn't show me that popup because it seemingly doesn't attempt to authenticate on said server so I just arrive at a "503 auth failed". Once it fails, it gets stuck there and I have to kill -9 it. Please consider that the page you get redirected to at step 2 in the wizard will require HTTP authentication.

**Comment by tiamat2012** [comment]
I had the same problem because we use SAML too.  As a temporary workaround, you can modify /Applications/YakYak 2.app/Contents/Resources/app/main.js to get the token manually:
```
    creds = function() {

      return {
         auth: Client.authStdin
      };
    //  var prom;
    //  prom = login(mainWindow);
    //  prom.then(function() {
    //    return loadAppWindow();
    //  });
    //  return {
    //    auth: function() {
    //      return prom;
    //    }
      };
    };
```

Then run the application once from a terminal window:

$ /Applications/YakYak\ 2.app/Contents/MacOS/YakYak

It will give you a URL to copy into a browser...  Then login with SAML in your domain.  For me, it returned a Welcome page with my name and a Sign In button.  When I clicked the Sign In button, it gave the the code needed which I pasted into the terminal window and YakYak started fine.  The library saves the token somewhere on your mac.

Once you do that, you can start YakYak from the icon in Launchpad.  If your token ever expires or is invalidated, you just have to run the app from the command line again to save a new token.

Now if I can learn enough about YakYak and the toolset to modify the login.js to handle this cleanly in the browser window.

**Comment by rcosma-gd** [comment]
Nice workaround :) am logged on, thank you!

**Comment by x-tk** [comment]
Would be nice to have this fixed, ty for workaround

**Comment by algesten** [comment]
ok. the original hangups has changed their way of doing auth. maybe that would solve this too.
